In [1]:
import numpy as np
import matplotlib as plt

## States in a Markov Process

In [2]:
state = { 0 : "STATE 1",
          1 : "STATE 2", 
          2 : "STATE 3" 
        } 

In [3]:
state

{0: 'STATE 1', 1: 'STATE 2', 2: 'STATE 3'}

In [4]:
A = np.array([[0.1, 0.4, 0.5], 
             [0.4, 0.5, 0.1], 
             [0.1, 0.1, 0.8]] 
            )

In [5]:
A

array([[0.1, 0.4, 0.5],
       [0.4, 0.5, 0.1],
       [0.1, 0.1, 0.8]])

## Random Walk on a Markov Chain 

In [6]:
n = 12

start_state = 1
print(state[start_state], "---->", end = " ")
previous_state = start_state 

while n-1:
    current_state = np.random.choice([0,1,2], p = A[previous_state])
    print(state[current_state], "---->", end = " ")
    current_state = previous_state
    n = n - 1 

STATE 2 ----> STATE 2 ----> STATE 1 ----> STATE 2 ----> STATE 2 ----> STATE 2 ----> STATE 2 ----> STATE 1 ----> STATE 1 ----> STATE 1 ----> STATE 3 ----> STATE 2 ----> 

## Simulation : Monte Carlo Method 

In [10]:
steps = 10**6
start_state = 1 
pi = np.array([0, 0, 0])
pi[start_state] = 1
previous_state = start_state 

i = 0

while i < steps: 
    current_state = np.random.choice([0,1,2], p = A[previous_state])
    pi[current_state] = pi[current_state] + 1
    previous_state = current_state 
    i = i + 1
    
print("The stationary probability distribution is : ", pi/steps)

The stationary probability distribution is :  [0.176517 0.254447 0.569037]


## SImulation : Matrix Multiplication 

In [7]:
steps = 10**6

A_n = A

i = 0
while i < steps: 
    A_n = np.matmul(A_n, A)
    i = i + 1

print(A_n)
print("The sationary probability distribution is: ", A_n[0])

[[0.17647059 0.25490196 0.56862745]
 [0.17647059 0.25490196 0.56862745]
 [0.17647059 0.25490196 0.56862745]]
The sationary probability distribution is:  [0.17647059 0.25490196 0.56862745]
